### ISSUE TITLE
TypeError: Cannot read property 'fpwr' of undefined

### ISSUE THREAD

**Issue by Nyaoki23** [lukasroegner/homebridge-dyson-pure-cool#115]
Hi, I want use "home bridge-dyson-pure-cool".
But there is a Error message in the log. This Error appear already turn on Dyson(TP02).

Please check the log:
Homebridge is running on port 51431.
[8/13/2020, 9:09:11 PM] TypeError: Cannot read property 'fpwr' of undefined
    at MqttClient.<anonymous> (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/src/dyson-pure-cool-device.js:497:41)
    at MqttClient.emit (events.js:314:20)
    at MqttClient._handlePublish (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:940:12)
    at MqttClient._handlePacket (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:305:12)
    at work (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:261:12)
    at Writable.writable._write (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:271:5)
    at doWrite (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:713:22)

I can't understand. Please tell me the solution.

**Comment by lukasroegner** [comment]
Please start Homebridge in debug mode (parameter `-D`) and provide the logs that occur around this issue, especially those that start with `MQTT message received` are important to track down the issue.

**Comment by Nyaoki23** [comment]
Thank you for read my issue.

OK. Please check a log:
[8/14/2020, 9:59:43 AM] Homebridge is running on port 51431.
[8/14/2020, 9:59:43 AM] [DysonPureCoolPlatform] NK4-JP-HFA2304A - MQTT connection established.
[8/14/2020, 9:59:44 AM] [DysonPureCoolPlatform] NK4-JP-HFA2304A - MQTT message received: {"msg":"CURRENT-STATE","time":"2020-08-14T00:59:42.000Z","mode-reason":"state-reason","MODE":"dial","OFF":"product-state","fmod":"OFF","fnst":"OFF","fnsp":"0004","qtar":"0004","oson":"OFF","rhtm":"ON","filf":"3687","ercd":"02C0","nmod":"OFF","wacd":"NONE","scheduler":{"srsc":"cb53","dstv":"0000","tzid":"0001"}}
[8/14/2020, 9:59:44 AM] TypeError: Cannot read property 'fpwr' of undefined
    at MqttClient.<anonymous> (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/src/dyson-pure-cool-device.js:497:41)
    at MqttClient.emit (events.js:314:20)
    at MqttClient._handlePublish (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:940:12)
    at MqttClient._handlePacket (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:305:12)
    at work (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:261:12)
    at Writable.writable._write (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:271:5)
    at doWrite (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:713:22)
[8/14/2020, 9:59:44 AM] Got SIGTERM, shutting down Homebridge...
[8/14/2020, 9:59:44 AM] [DysonPureCoolPlatform] NK4-JP-HFA2304A - MQTT connection ended.
[8/14/2020, 9:59:44 AM] [DysonPureCoolPlatform] NK4-JP-HFA2304A - MQTT disconnected.

Is this all right?

**Comment by lukasroegner** [comment]
Thanks! The response format looks strange, are there any updates for the Dyson that you haven't applied?

**Comment by Nyaoki23** [comment]
Hi! I can use your plugin!
But, I don't change parameters.

Please check the log. Is this all right? :
[8/14/2020, 6:50:03 PM] Homebridge is running on port 51431.
[8/14/2020, 6:50:03 PM] [DysonPureCoolPlatform] NK4-JP-HFA2304A - MQTT connection established.
[8/14/2020, 6:50:03 PM] [DysonPureCoolPlatform] NK4-JP-HFA2304A - MQTT message received: {"msg":"CURRENT-STATE","time":"2020-08-14T09:50:01.000Z","mode-reason":"","state-reason":"MODE","dial":"OFF","rssi":"-43","product-state":{"fmod":"FAN","fnst":"FAN","fnsp":"0007","qtar":"0004","oson":"ON","rhtm":"ON","filf":"3680","ercd":"02C0","nmod":"OFF","wacd":"NONE"},"scheduler":{"srsc":"cb53","dstv":"0000","tzid":"0001"}}
[8/14/2020, 6:50:03 PM] [DysonPureCoolPlatform] NK4-JP-HFA2304A - MQTT message received: {"msg":"ENVIRONMENTAL-CURRENT-SENSOR-DATA","time":"2020-08-14T09:50:02.000Z","data":{"tact":"OFF","hact":"OFF","pact":"0001","vact":"0000","sltm":"OFF"}}
[8/14/2020, 6:50:28 PM] [DysonPureCoolPlatform] NK4-JP-HFA2304A - set Active to 0: {"fpwr":"OFF","fmod":"OFF"}
[8/14/2020, 6:50:28 PM] [DysonPureCoolPlatform] NK4-JP-HFA2304A - MQTT message received: {"msg":"STATE-CHANGE","time":"2020-08-14T09:50:27.000Z","mode-reason":"","state-reason":"MODE","product-state":{"fmod":["FAN","OFF"],"fnst":["FAN","OFF"],"fnsp":["0007","0007"],"qtar":["0004","0004"],"oson":["ON","OFF"],"rhtm":["ON","ON"],"filf":["3680","3680"],"ercd":["02C0","02C0"],"nmod":["OFF","OFF"],"wacd":["NONE","NONE"]},"scheduler":{"srsc":"cb53","dstv":"0000","tzid":"0001"}}

**Comment by lukasroegner** [comment]
Yes, this is correct. It seems that your device needed a firmware update.

**Comment by Nyaoki23** [comment]
Hmm, OK.
Thank you for your quick response!
Have a good day!
