### ISSUE TITLE
Still API 400 error, blank page in credentials website (v2.0.1)

### ISSUE THREAD

**Issue by magnusalex** [lukasroegner/homebridge-dyson-pure-cool#189]
After 2.0.1 update I still get the API 400 error. After typing in my details in the credentials website and I click "Next", the page goes blank and no info comes up (ERR_CONNECTION_REFUSED browser error).

I find this in the logs:

```
[5/23/2021, 12:27:22 PM] TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received null
    at Decipheriv.update (internal/crypto/cipher.js:157:11)
    at Request._callback (/homebridge/node_modules/homebridge-dyson-pure-cool/src/credentials-generator-website.js:449:54)
    at Request.self.callback (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/request/request.js:185:22)
    at Request.emit (events.js:376:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:376:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:482:28)
    at IncomingMessage.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
```

Any ideas or suggestions?

**Comment by lukasroegner** [comment]
I've published a new version (2.0.2) with additional debug output for the credentials generator. Please update the plugin and start Homebridge it in debug mode (parameter `-D`).

When using the credentials generator website, you'll get logs from the plugin with the raw response of the Dyson API. Please check for the logs that occur before you error. They should look like this:

```
[DysonPureCoolPlatform] [ { Serial: 'XXX-XX-XXXXXXXX',
    Name: 'XXX',
    Version: 'XXXX',
    LocalCredentials: 'XXXX',
    AutoUpdate: false,
    NewVersionAvailable: false,
    ProductType: 'XXX',
    ConnectionType: 'wss' } ]
```

Please post this log entry here so that I can check for the issue. Make sure you sanitize the log entry before posting.

**Comment by magnusalex** [comment]
Thank you! That kinda solved it, as I got the credentials from the new log entry. It also made me think about a possible cause. I have a couple of lamps in the same account. The new log entry is (the two units on top are Lightcycle lamps):

```
[5/24/2021, 11:22:08 PM] [DysonPureCoolPlatform] [
  {
	Serial: 'E5V-EU-xxxxxxxx',
	Name: 'xxxx',
	Version: '0552PF.00.05.017.0002',
	LocalCredentials: null,
	AutoUpdate: true,
	NewVersionAvailable: false,
	ProductType: '552',
	ConnectionType: 'wss'
  },
  {
	Serial: 'YS2-EU-xxxxxxxx',
	Name: 'xxxx',
	Version: '0552PF.00.05.017.0002',
	LocalCredentials: null,
	AutoUpdate: true,
	NewVersionAvailable: false,
	ProductType: '552',
	ConnectionType: 'wss'
  },
  {
	Serial: 'VS9-EU-xxxxxxxx',
	Name: 'xxxx',
	Version: 'ECG2PF.02.06.003.0002',
	LocalCredentials: 'xxxxxxxxxxxxxxxxxxxxxxxx......',
	AutoUpdate: true,
	NewVersionAvailable: true,
	ProductType: '438',
	ConnectionType: 'wss'
  }
]
```
Thanks for your prompt help, by the way!

**Comment by lukasroegner** [comment]
@magnusalex The value for "LocalCredentials" is not the same as for the "credentials" in the config. However, I found the issue by looking at your logs: for Lightcycle devices, the "LocalCredentials" is empty. This is fixed with the latest version!

**Comment by magnusalex** [comment]
Confirmed! Works, and everything is well :)
