### ISSUE TITLE
Dyson plug-in crashing hoobs 

### ISSUE THREAD

**Issue by dd3uk** [lukasroegner/homebridge-dyson-pure-cool#212]
See logs below .. it seems the Dyson plug-in is crashing hoobs… tried Googling for this and looked on here but can’t see anything out there. Any advice appreciated 

15/09/2021, 00:45:49 Initializing HAP-NodeJS v0.9.4...
15/09/2021, 00:45:56 Loaded plugin 'homebridge-dyson-pure-cool'
15/09/2021, 00:45:56 [9/14/2021, 5:45:56 PM] Registering platform 'homebridge-dyson-pure-cool.DysonPureCoolPlatform'
15/09/2021, 00:45:56 Loaded plugin 'homebridge-neato'
15/09/2021, 00:45:56 [9/14/2021, 5:45:56 PM] Registering platform 'homebridge-neato.NeatoVacuumRobot'
15/09/2021, 00:45:56 Loading 2 platforms...
15/09/2021, 00:45:56 [DysonPureCoolPlatform] Initializing DysonPureCoolPlatform platform...
15/09/2021, 00:45:56 [NeatoVacuumRobot] Initializing NeatoVacuumRobot platform...
15/09/2021, 00:45:56 [NeatoVacuumRobot] Refresh is set to: auto
15/09/2021, 00:45:58 [DysonPureCoolPlatform] Accessories initialized.
15/09/2021, 00:45:58 Error: listen EADDRINUSE: address already in use 0.0.0.0:48000
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at doListen (net.js:1500:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
15/09/2021, 00:45:59 Got SIGTERM, shutting down Bridge...

**Comment by dd3uk** [comment]
Ok, so I messed about and changed the port number for credentials to 48001 .. no clue of that’ll break anything else but the bridge started working 🤷🏼‍♂️
