### ISSUE TITLE
DYSON PH01 Pure Humidify + Cool | stops responding via homebridge | characteristic was supplied illegal value

### ISSUE THREAD

**Issue by argonmember** [lukasroegner/homebridge-dyson-pure-cool#218]
**Overnight the PH01 no longer works via Homebridge. (see Debug Message)
The buttons in Apple Home and Homebridge no longer work.
The PH01 can still be controlled normally via the Dyson app.
Resetting the PH01, removing it from the Dyson app and reconfiguring the plug-in were unsuccessful.**

Another Dyson (Dyson TP01 Pure Cool) continues to work without any problems.

**[11/3/2021, 12:20:50 PM] [homebridge-dyson-pure-cool] This plugin generated a warning from the characteristic 'Relative Humidity Humidifier Threshold': characteristic was supplied illegal value: number 0 exceeded minimum of 30. See https://git.io/JtMGR for more info.**
[11/3/2021, 12:20:50 PM] [homebridge-dyson-pure-cool] Error: 
    at RelativeHumidityHumidifierThreshold.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2074:105)
    at RelativeHumidityHumidifierThreshold.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1982:16)
    at RelativeHumidityHumidifierThreshold.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1535:21)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at RelativeHumidityHumidifierThreshold.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:656:38)
    at RelativeHumidityHumidifierThreshold.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2139:22)
[11/3/2021, 12:20:51 PM] [DysonPureCoolPlatform] XXX-EU-XXXXXXXX - MQTT disconnected.
[11/3/2021, 12:20:52 PM] [DysonPureCoolPlatform] XXX-EU-XXXXXXXX - MQTT reconnecting.
[11/3/2021, 12:20:54 PM] [DysonPureCoolPlatform] XXX-EU-XXXXXXXX - MQTT disconnected.
[11/3/2021, 12:20:55 PM] [DysonPureCoolPlatform] XXX-EU-XXXXXXXX - MQTT reconnecting.

**Homebridge on Synology NAS
OS | Alpine Linux (3.12.7)
Node.js Version v14.17.5
Npm Version 6.14.14
homebridge-dyson-pure-cool v2.0.3**

**Comment by argonmember** [comment]
After Homebride was automatically updated to version 1.3.6, the Dyson PH01 was accessible again and could be controlled as usual.
