### ISSUE TITLE
BP03: TypeError: Cannot read properties of undefined (reading '1')

### ISSUE THREAD

**Issue by 6illess** [lukasroegner/homebridge-dyson-pure-cool#333]
Dyson Purifier Big+Quiet Formaldehyde makes Homebridge crash when turning it on/off via this plugin.
I haven't enabled any additional settings within the plugin config.
Strange thing is that the command on/off does get through and thus the Dyson reacts on it but it makes the application crash immediately:

[2/17/2024, 11:14:01 AM] [DysonPureCoolPlatform] T7A-EU-******** - set Active to 0: {"fpwr":"OFF","fmod":"OFF"}
[2/17/2024, 11:14:01 AM] TypeError: Cannot read properties of undefined (reading '1')
    at MqttClient.<anonymous> (/homebridge/node_modules/homebridge-dyson-pure-cool/src/dyson-pure-cool-device.js:675:111)
    at MqttClient.emit (node:events:514:28)
    at MqttClient._handlePublish (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:940:12)
    at MqttClient._handlePacket (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:305:12)
    at work (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:261:12)
    at Writable.writable._write (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:271:5)
    at doWrite (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (node:internal/streams/readable:985:22)
[2/17/2024, 11:14:01 AM] Got SIGTERM, shutting down Homebridge...

**Comment by 6illess** [comment]
Closing this issue as it’s fixed, thanks !
