### ISSUE TITLE
Homebridge v2.0.0 beta

### ISSUE THREAD

**Issue by donavanbecker** [lukasroegner/homebridge-dyson-pure-cool#341]
```
/usr/local/lib/node_modules/homebridge-dyson-pure-cool/src/dyson-pure-cool-device.js:173
            unit: Characteristic.Units.PERCENTAGE
                                       ^
TypeError: Cannot read properties of undefined (reading 'PERCENTAGE')
    at new DysonPureCoolDevice (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/src/dyson-pure-cool-device.js:173:40)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/src/dyson-pure-cool-platform.js:97:35)
    at HomebridgeAPI.emit (node:events:519:28)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:271:10)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:194:14)
```

**Comment by donavanbecker** [comment]
Fixed with #342

**Comment by lukasroegner** [comment]
Fixed version 2.7.12 is now available on NPM.
