### ISSUE TITLE
Crashing on toggle change on 2.8.1

### ISSUE THREAD

**Issue by andreaskas** [lukasroegner/homebridge-dyson-pure-cool#351]
set AutoMode to true: {"auto":"ON","fmod":"AUTO"}

/var/lib/homebridge/node_modules/homebridge-dyson-pure-cool/src/dyson-pure-cool-device.js:722
                autoModeSwitchService.updateCharacteristic(Characteristic.On, content['product-state']['fmod'][1] === 'AUTO');
                                                                                                              ^
TypeError: Cannot read properties of undefined (reading '1')
    at MqttClient.<anonymous> (/var/lib/homebridge/node_modules/homebridge-dyson-pure-cool/src/dyson-pure-cool-device.js:722:111)
    at MqttClient.emit (node:events:519:28)
    at MqttClient._handlePublish (/var/lib/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:940:12)
    at MqttClient._handlePacket (/var/lib/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:305:12)
    at work (/var/lib/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:261:12)
    at Writable.writable._write (/var/lib/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:271:5)
    at doWrite (/var/lib/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/var/lib/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/var/lib/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (node:internal/streams/readable:1007:22)
    
@lukasroegner     I think it's related to #332 since everything is working fine at 2.8.0. For now i reverted back to 2.8.0 and error is gone

**Comment by lukasroegner** [comment]
@andreaskas I think I found the issue, new version 2.8.2 is available on NPM.

**Comment by andreaskas** [comment]
@lukasroegner yes 2.8.2 seems to fix the issue.  Thank you!
