### ISSUE TITLE
non-empty displayName

### ISSUE THREAD

**Issue by slug2020** [lukasroegner/homebridge-dyson-pure-cool#46]
Hi and thanks for this plug-in. I get the following error after installing it:

`Error: Accessories must be created with a non-empty displayName.
    at new PlatformAccessory (/usr/local/lib/node_modules/homebridge/lib/platformAccessory.js:15:27)
    at new DysonPureCoolDevice (/homebridge/node_modules/homebridge-dyson-pure-cool/src/dyson-pure-cool-device.js:75:32)
    at Request._callback (/homebridge/node_modules/homebridge-dyson-pure-cool/src/dyson-pure-cool-platform.js:196:39)
    at Request.self.callback (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:321:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:427:28)
    at IncomingMessage.emit (events.js:333:22)`

**Comment by lukasroegner** [comment]
Hi @slug2020,

It seems that the Dyson API does not return a name for one of your devices. Can you check via the Dyson API if all your devices have names set? Maybe the API has an issue with special characters in device names, do you have any special characters in the device names?

**Comment by slug2020** [comment]
you were right, one of my Dyson fans wasn't assigned to a room within the Dyson app. 

I don't see any issues in the log, but I can't control the fan. I don't see the temperature / humidity from the sensor and no changes made in the home app are applied to the fan. 

Any suggestion? I try to control the dyson dp04 fan.

**Comment by lukasroegner** [comment]
Please start homebridge in debug mode (parameter -D) and check the logs for MQTT messages.
