### ISSUE TITLE
Invalid device credentials after copying credentials printed in log

### ISSUE THREAD

**Issue by HammerAce42** [lukasroegner/homebridge-dyson-pure-cool#73]
This is a non-blocking issue, but it's a curious one:

I have 3 Dyson Pure devices, (1 x HP04, 2x HP02). I copied the credentials into the config for each of those devices, but one of the devices (an HP02) consistently reports invalid credentials with the following message printed in the logs:

[DysonPureCoolPlatform] Invalid device credentials for device with serial number [Serial number redacted]. Make sure you copied it correctly

The plugin recovers gracefully by falling back on the Dyson API, but I am still perplexed why that one credential is failing. I have copied it multiple times and triple checked that I am copying the right one for that serial number. I've also checked that the character count in the credential length matches the one for the other HP02 with the working credential (HP04 credential has a different length, but that doesn't surprise me).

I have reset my entire homebridge instance (for unrelated issues) and this oddity has survived that reset. Reordering the devices in the config, or even deleting the other HP02 device entirely does not help.

Any ideas what might be going on?

**Comment by lukasroegner** [comment]
Hi @HammerAce42,

I would try:
1. Remove the two working devices from the config
2. Remove the `credentials` entry from the non-working device in the config
3. Run `homebridge` to get the credentials in the logs
4. Copy them into the config and try again

If that all doesn't work, I can take a deeper look at your configuration, however, we should do that on a private channel, as it wouldn't help of you post the sanitized config here in GitHub.

**Comment by HammerAce42** [comment]
Tried that and still get the invalid credential error.

Unfortunately, I now have a bigger, blocking issue. I had enabled the "-K" (keep accessories for uninstalled plugins) homebridge flag with the hope that the automations associated with the working devices would not need to be recreated after the temporary removal of the devices for this exercise. Unfortunately, when I re-added the config entries for the working devices, I started getting this error:

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: c851ab84-ca35-481c-96ec-cfb564f53328
    at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:413:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:309:19
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:269:69)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:157:10)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

I have been unable to clear the error despite starting homebridge without the -K flag and uninstalling and reinstalling the plugin. The only way I am able to avoid the error is to keep both of the "working" devices out of the config file (I have tried combinations of trying to add only one of the working devices back, and it always fires the same error).

Interestingly, even when both working devices are removed from the config and remaining devices is working fine, I still see a message in the log about the removed devices:

[DysonPureCoolPlatform] No IP address provided for device with serial number [Serial number 1]
[DysonPureCoolPlatform] No IP address provided for device with serial number [Serial number 2]

Perhaps the plugin isn't correctly clearing removed devices when homebridge is launched with the -K flag, causing this issue? I hope there is a fix other than a full reset of the homebridge instance! Any help appreciated.

Thanks!

**Comment by HammerAce42** [comment]
There is another nuance which is perplexing. Once I have tried adding either of the removed entries back and starting getting the error mentioned earlier, the only way to stop the error is to uninstall the plugin. Just removing the offending config entries doesn't help.

**Comment by HammerAce42** [comment]
I tried manually modifying the cachedAccessories file to resolve the duplicate UUID issue, but that failed and led some other accessories to also get cleared so I gave in and did another Homebridge reset. All 3 units are working again, modulo the credential issue I reported in the first post of this bug.

**Comment by HammerAce42** [comment]
Spoke to soon - I started noticing the homebridge process was frequently getting restarted whenever I tried to make a change to one of the accessories where the credential was working. Inspecting the log, I see that each command was being duplicated:

```
[5/2/2020, 10:24:19 PM] [DysonPureCoolPlatform] [Device Serial number] - set NightMode to true: {"nmod":"ON"}
[5/2/2020, 10:24:19 PM] [DysonPureCoolPlatform] [Device Serial number]  - set NightMode to true: {"nmod":"ON"}
[5/2/2020, 10:24:19 PM] Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at Characteristic.<anonymous> (/homebridge/node_modules/homebridge-dyson-pure-cool/src/dyson-pure-cool-device.js:703:13)
    at Characteristic.emit (events.js:322:22)
    at Characteristic.EventEmitter.emit (domain.js:482:12)
    at Characteristic.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:614:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1441:24
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1283:10)
    at HAPServer.emit (events.js:310:20)
    at HAPServer.EventEmitter.emit (domain.js:482:12)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:956:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:307:24)
    at IncomingMessage.emit (events.js:310:20)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at Characteristic.<anonymous> (/homebridge/node_modules/homebridge-dyson-pure-cool/src/dyson-pure-cool-device.js:703:13)
    at Characteristic.emit (events.js:322:22)
    at Characteristic.EventEmitter.emit (domain.js:482:12)
    at Characteristic.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:614:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1441:24
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1283:10)
    at HAPServer.emit (events.js:310:20)
    at HAPServer.EventEmitter.emit (domain.js:482:12)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:956:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:307:24)
    at IncomingMessage.emit (events.js:310:20)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[5/2/2020, 10:24:19 pm] [SmartThings-v2] ERROR: uncaughtException: This callback function has already been called by someone else; it can only be called one time.
Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at Characteristic.<anonymous> (/homebridge/node_modules/homebridge-dyson-pure-cool/src/dyson-pure-cool-device.js:703:13)
    at Characteristic.emit (events.js:322:22)
    at Characteristic.EventEmitter.emit (domain.js:482:12)
    at Characteristic.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:614:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1441:24
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1283:10)
    at HAPServer.emit (events.js:310:20)
    at HAPServer.EventEmitter.emit (domain.js:482:12)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:956:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:307:24)
    at IncomingMessage.emit (events.js:310:20)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[5/2/2020, 10:24:19 PM] Got SIGTERM, shutting down Homebridge...
```
It seems like this issue only occurs if one has the credential in the config file AND the plugin falls back on the Dyson API due to a non-working credential for another machine. When I removed the credentials for these machines, the issue disappeared.

Hopefully this saga of troubles that I mostly created for myself helps in improving the plugin in some way :)

Thanks for your efforts!

**Comment by lukasroegner** [comment]
@HammerAce42, I enhanced the error handling when parsing the credentials of all configured devices. The whole process is stopped if an error has been found, so that the duplicate UUID issue should no longer occur.

**Comment by HammerAce42** [comment]
Thanks for fixing this! The invalid credential issue continues, but I can live with that since practically it doesn't affect much.

I am curious, was the fact that I had credentials in my config despite the plugin falling back to the Dyson API causing the duplicate uuid issue?

**Comment by HammerAce42** [comment]
@lukasroegner, let me know what private channel we can use to further diagnose the credential issue.

**Comment by lukasroegner** [comment]
@HammerAce42 I'm sorry, but I cannot provide in-depth debugging of personal setups, I honestly don't have the time to do so. What I can do for you is to take a look at your credentials: copy them over to an online JavaScript Base64 decoder (e.g. https://decodebase64.com). The decoded output is a JSON object. You can sanitize the password property of the JSON before posting here.

**Comment by HammerAce42** [comment]
@lukasroegner Not a problem - the information you provided helped me find the issue. The device name had a `'` character (since it was named after my kid whose room the device is in), which seemed to be the culprit (it appeared malformed in the ASCII version decoded from the base64 credential: it read as `"Name":"[My kid's name]âs Room"`). I changed the device name to remove the character, and it now works as intended.

Thanks for your help and efforts!
